jobs:


      
#MANIFESTS
      
  - name: allpl-manifestN1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
      - TASK: managed
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-manifestbg1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
     # - IN: test-time
      
 
  - name: allpl-manifest5
    type: manifest
    steps:
      - IN: allpl-image1
        #versionNumber: 1000
      - IN: allpl-tg1
      
      
  - name: testallpl-tpdeployNOTIFY1
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      - IN: allpl-dopts
      - IN: allpl-tripubcluster
      - IN: allpl-image1
      - IN: foo-resource
        #versionNumber: 1000
      
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-ddcdeploy1
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ddccluster
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-dcldeploy1
    type: deploy
    steps:
      - IN: allpl-manifest5
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-dclcluster
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-ecsdeployup11
    type: deploy
    steps:
      - IN: allpl-manifest5
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      #- IN: test-time-2
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  - name: testallpl-gkedeployup11
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-gkecluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testnotify4
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      #- IN: test-time-1
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  #RELEASE

  - name: allpl-release11
    type: release
    steps:
      - IN: allpl-version
         #versionName: testrelease
      - TASK: managed
        bump: beta
      - IN: allpl-tg3
    flags:
      - release_allpl
  #   on_start:
  #     - NOTIFY: allpl-email
  #     #- NOTIFY: allpl-irc
  #   on_success:
  #     - NOTIFY: allpl-email
  #     - NOTIFY: allpl-slack
  #     #- NOTIFY: allpl-irc
