jobs:


      
#MANIFESTS
      
  - name: allpl-manifestN11
    type: manifest
    steps:
     # - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-dopts
      - IN: allpl-tg1
      - TASK: managed
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack

      
  
      
  
  
      
  - name: testallpl-ecsdeployup11
    type: deploy
    steps:
      - IN: allpl-manifestN11
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      #- IN: test-time-2
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      #- NOTIFY: allpl-email2
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  - name: testallpl-dcldeployn1
    type: deploy
    steps:
     # - IN: allpl-manifestN11
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: foo-resource
      - IN: allpl-dclcluster
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
    #  - NOTIFY: allpl-slack
  - name: runShkn1
    type: runSh
  #  serial: true
    steps:
      - IN: allpl-sample-script
      - IN: allpl-tg2
      - TASK:
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    
  - name: testnotify4
    type: runSh
    steps:
      - IN: allpl-sample-script
      - IN: allpl-version
      - IN: allpl-manifestN11
      - IN: allpl-dopts
      - IN: allpl-scale2 #REPLICA
      - OUT: allpl-image1
      - IN: testallpl-ecsdeployup11
    
     
        #versionName: theyrev
       # versionNumber: 298000
      - IN: allpl-tg2
     
      #- IN: test-time-1
      - TASK:
        - script: ls
       # - script: pwd
        - script: echo "$foo"
        - script: echo "$m1"
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    #on_start:
     # - NOTIFY: allpl-slack
     # - NOTIFY: allpl-email
     # - script: echo 'test start'
    #on_success:
     # - NOTIFY: allpl-slack
     # - NOTIFY: allpl-email
     # - script: echo 'infra test'
     # - script: echo 'newtesting success'
     # - script: pwd
     # - script: ls
     # - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    #on_failure:
     # - script: echo 'testing1 failure'
     # - script: echo 'failure runSh'
     # - script: ls
     # - NOTIFY: allpl-slack
     # - NOTIFY: allpl-email
   
