jobs:

#RELEASE

   - name: allpl-release11
     type: release
     steps:
       - IN: allpl-version
         #versionName: testrelease
       - TASK: managed
         bump: beta
       - IN: allpl-tg3
     flags:
       - release_allpl
  #   on_start:
  #     - NOTIFY: allpl-email
  #     #- NOTIFY: allpl-irc
  #   on_success:
  #     - NOTIFY: allpl-email
  #     - NOTIFY: allpl-slack
  #     #- NOTIFY: allpl-irc
      
#MANIFESTS
      
  - name: allpl-manifestN1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
      - TASK: managed
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: allpl-manifestbg1
    type: manifest
    steps:
      - IN: allpl-image1
       # versionNumber: 100
      - IN: allpl-tg1
     # - IN: test-time
      
  # - name: allpl-manifest2invalidtag
  #   type: manifest
  #   steps:
  #     - IN: allpl-image3invalidtag
  #     # versionNumber: 100
  #     - IN: allpl-tg2
      
  # - name: allpl-manifest3invalidformat
  #   type: manifest
  #   steps:
  #     - IN: allpl-image4invalidformat
  #     # versionNumber: 100
  #     - IN: allpl-tg3
      
  # - name: allpl-manifest4invalidrepo
  #   type: manifest
  #   steps:
  #     - IN: allpl-image2invalidimg
  #     # versionNumber: 100
  #     - IN: allpl-tg3
      
  - name: allpl-manifest5
    type: manifest
    steps:
      - IN: allpl-image1
        #versionNumber: 1000
      - IN: allpl-tg1
      
  # - name: allpl-manifest2multiimg
  #   type: manifest
  #   steps:
  #     - IN: fl-image2
  #     - IN: fl-image7workingdir
  #     - IN: fl-dopts
  #       applyTo:
  #         - fl-image2
  #     - IN: fl-tg2
      
  - name: testallpl-tpdeployNOTIFY1
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      - IN: allpl-dopts
      - IN: allpl-tripubcluster
      - IN: allpl-image1
      - IN: foo-resource
        #versionNumber: 1000
      
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-ddcdeploy1
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ddccluster
    on_start:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-dcldeploy1
    type: deploy
    steps:
      - IN: allpl-manifest5
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-dclcluster
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-ecsdeployup11
    type: deploy
    steps:
      - IN: allpl-manifest5
      #  switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      #- IN: test-time-2
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testallpl-gkedeployup11
    type: deploy
    steps:
      - IN: allpl-manifest5
       # switch: off
      # - IN: fl-manifest2multiimg
      #   switch: off
      - IN: allpl-dopts
      - IN: allpl-gkecluster
      - TASK: managed
        deployMethod: upgrade
    on_success:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
    on_failure:
      - NOTIFY: allpl-email
      - NOTIFY: allpl-slack
      
  - name: testnotify4
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      #- IN: test-time-1
      - TASK:
        - script: ls
        - script: ./IN/allpl-sample-script/gitRepo/echo.sh
    on_start:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
    on_success:
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      - script: echo 'infra test'
      - script: echo 'newtesting success'
    on_failure:
      - script: echo 'testing1 failure'
      - script: echo 'failure runSh'
      - NOTIFY: allpl-slack
      - NOTIFY: allpl-email
      
  - name: testY2
    type: runSh
    steps:
      - IN: allpl-sample-script
      # versionName: testsha
      - IN: allpl-tg2
      - TASK:
        - script: ls

      
 # - name: INtest
  #  type: runSh
   # steps:
    #  - IN: allpl-sample-script
     #   versionNumber: 2
      # versionName: testsha
      #- IN: allpl-tg2
      #- IN: testY1
      #- TASK:
       # - script: ls
        #- script: ./IN/allpl-sample-script/gitRepo/echo.sh
        
  - name: testbg7
    type: deploy
    steps:
      - IN: allpl-manifestbg1
      - IN: allpl-dopts
      - IN: allpl-ecscluster
      
  #- name: allpl-faile test
   # type: manifest
    #steps:
     # - IN: allpl-image1
       # versionNumber: 100
      #- IN: allpl-tg1
     # - IN: test-time-1

  # - name: outrunsh
  #   type: runSh
  #   steps:
  #     - TASK:
  #       - script: "mkdir -p /build/state/" # creating directory 
  #       - script: "touch /build/state/allpl-image1.env" # touch will create new empty file with timestamp
  #       - script: "echo 'Hello'"
  #     # - script: "echo 'versionName=latest' >>  /build/state/rs-img1.env" # this will be adding in the file mongo-image.env
  #       #- script: "echo 'anotherProperty=foo' >>  /build/state/rs-img1.env" # next line will be this in the file mongo-image.env
  #     - OUT: allpl-image1
  #     - IN: allpl-tg2
       
  # - name: inrunsh2
  #   type: runSh
  #   steps:
  #     - IN: allpl-sample-script
  #     # versionName: testsha
  #     - IN: allpl-tg2
  #     - TASK:
  #       - script: ./IN/allpl-sample-script/gitRepo/echo.sh
      
  # - name: allpl-gkedeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg1
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg2
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest3invalidformat
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest2invalidtag
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
      
  # - name: allpl-gkedeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-gkedeploybg3
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
      
  # - name: allpl-ecsdeployup4
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-gkecluster
  #     - TASK: managed
  #       deployMethod: upgrade
        
  # - name: allpl-ecsdeploybg5
  #   type: deploy
  #   steps:
  #     - IN: allpl-manifest4invalidrepo
  #     - IN: allpl-dopts
  #     - IN: allpl-ecscluster
  
